default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-41608_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima-41608_test

production:
  <<: *default
  database: furima_41608_production
  username: furima_41608
  password: <%= ENV["FURIMA_41608_DATABASE_PASSWORD"] %>